import type { BoardModel, EngineWarning, LayerId, Vec2 } from '../model/types';
import { buildLayerToolpath } from '../toolpath/assemble';
import { applyMinimumWidths } from '../toolpath/widening';
import { arcPoint, type PathSegment } from '../toolpath/segments';
import { distance } from '../geometry/primitives';
import * as g from './format';
import { createOutputTransform, type OutputTransform } from './transforms';
import { effectiveToolDiameterMm, type GCodeSettings } from './settings';

/** Different-net copper keeps at least this gap even with a very fine tool. */
const MINIMUM_CLEARANCE_MM = 0.1;

export interface GCodeFile {
	fileName: string;
	/** Human-readable purpose shown in the download list. */
	label: string;
	kind: 'isolation-top' | 'isolation-bottom' | 'drill' | 'registration';
	drillDiameterMm?: number;
	content: string;
}

export interface GenerateResult {
	files: GCodeFile[];
	warnings: EngineWarning[];
	/** The board as machined: thin tracks/pads widened (clearance-capped). */
	board: BoardModel;
}

/** Generate every output file for a board. */
export function generateGCode(
	designedBoard: BoardModel,
	boardName: string,
	settings: GCodeSettings,
	generatedAt: Date
): GenerateResult {
	const warnings: EngineWarning[] = [];
	const files: GCodeFile[] = [];
	const extension = settings.fileExtension || '.txt';

	// Widen thin copper toward the configured minimums first, capped so
	// different-net features keep an isolation channel between them.
	const widening = applyMinimumWidths(designedBoard, {
		minimumTrackWidthMm: settings.minimumTrackWidthMm,
		minimumPadDiameterMm: settings.minimumViaSizeMm,
		clearanceMm: Math.max(effectiveToolDiameterMm(settings), MINIMUM_CLEARANCE_MM)
	});
	const board = widening.board;
	warnings.push(...widening.warnings);

	for (const layer of ['top', 'bottom'] as const) {
		const { lines, warnings: layerWarnings } = isolationFile(
			board,
			boardName,
			settings,
			layer,
			generatedAt
		);
		warnings.push(...layerWarnings);
		files.push({
			fileName: `${boardName}-${layer}-isolation${extension}`,
			label: layer === 'top' ? 'Top isolation engraving' : 'Bottom isolation engraving (mirrored)',
			kind: layer === 'top' ? 'isolation-top' : 'isolation-bottom',
			content: lines.join('\n') + '\n'
		});
	}

	if (settings.registrationHoles.enabled) {
		files.push(registrationFile(board, boardName, settings, generatedAt, extension));
	}

	for (const file of drillFiles(board, boardName, settings, generatedAt, extension)) {
		files.push(file);
	}

	return { files, warnings, board };
}

function header(
	boardName: string,
	fileType: string,
	side: string,
	generatedAt: Date,
	extraLines: string[] = []
): string[] {
	return [
		`( ${boardName} ${fileType} GCode )`,
		`( Side: ${side} )`,
		...extraLines,
		`( Generated Timestamp: ${generatedAt.toISOString()} )`,
		'( Generated by KiCadToGCode )'
	];
}

function initialize(settings: GCodeSettings, safeZ: number, spindleRPM: number): string[] {
	return [
		g.useUnits(settings.outputUnits),
		g.absoluteCoordinates,
		g.xyPlane,
		g.rapidZ(safeZ),
		g.rapidXY(0, 0, settings.useMachineRapids ? undefined : settings.xyRapidSpeed),
		g.startSpindle(spindleRPM),
		g.pause
	];
}

function tearDown(settings: GCodeSettings, safeZ: number): string[] {
	return [
		g.rapidZ(safeZ),
		g.rapidXY(0, 0, settings.useMachineRapids ? undefined : settings.xyRapidSpeed),
		g.stopSpindle,
		g.endProgram
	];
}

/** A toolpath segment mapped into machine output coordinates. */
interface OutputSegment {
	start: Vec2;
	end: Vec2;
	arc: {
		center: Vec2;
		/** True when the machine sees this arc as clockwise start → end. */
		clockwise: boolean;
	} | null;
}

function toOutputSegments(segments: PathSegment[], transform: OutputTransform): OutputSegment[] {
	return segments.map((segment) => {
		if (segment.kind === 'line') {
			return {
				start: transform.point(segment.start),
				end: transform.point(segment.end),
				arc: null
			};
		}
		return {
			start: transform.point(arcPoint(segment, segment.startAngle)),
			end: transform.point(arcPoint(segment, segment.endAngle)),
			arc: {
				center: transform.point(segment.center),
				// Model arcs travel clockwise; each mirror flips the handedness.
				clockwise: !transform.mirrored
			}
		};
	});
}

function isolationFile(
	board: BoardModel,
	boardName: string,
	settings: GCodeSettings,
	layer: LayerId,
	generatedAt: Date
): { lines: string[]; warnings: EngineWarning[] } {
	const warnings: EngineWarning[] = [];
	const toolDiameter = effectiveToolDiameterMm(settings);
	const sideMirror = layer === 'bottom' && settings.mirrorBottom;
	const transform = createOutputTransform(settings, board.width, board.height, sideMirror);

	const sideNote =
		layer === 'bottom' && settings.mirrorBottom
			? ['( Mirrored for flip-over machining: flip the blank left-over-right )']
			: [];
	const lines = [
		...header(boardName, 'Isolation', layer === 'top' ? 'Top' : 'Bottom', generatedAt, [
			...sideNote,
			`( Tool: ${toolDiameter.toFixed(3)} mm effective diameter, ${settings.isolationPasses} pass${settings.isolationPasses === 1 ? '' : 'es'} )`
		]),
		...initialize(settings, settings.isolationSafeZ, settings.isolationSpindleRPM)
	];

	let position: Vec2 = { x: 0, y: 0 };
	let firstCut = true;

	for (let pass = 0; pass < Math.max(1, settings.isolationPasses); pass++) {
		const isolationOffset = toolDiameter / 2 + pass * settings.isolationStepover * toolDiameter;
		// Minimum widths were already applied (clearance-capped) to the board;
		// clamping again here could undo a cap and short the board.
		const toolpath = buildLayerToolpath(board, layer, {
			isolationOffset,
			minimumTrackWidth: 0,
			minimumPadDiameter: 0
		});
		if (pass === 0) {
			warnings.push(...toolpath.warnings);
		}
		if (settings.isolationPasses > 1) {
			lines.push(`( Pass ${pass + 1}: offset ${isolationOffset.toFixed(3)} mm )`);
		}
		position = walkSegments(
			toOutputSegments(toolpath.segments, transform),
			position,
			firstCut,
			settings,
			lines
		);
		firstCut = false;
	}

	lines.push(...tearDown(settings, settings.isolationSafeZ));
	return { lines, warnings };
}

/**
 * Greedy nearest-neighbour walk: repeatedly cut the unprocessed segment whose
 * nearest endpoint is closest to the tool, lifting to safe Z only between
 * discontinuous segments. Returns the final tool position.
 */
function walkSegments(
	segments: OutputSegment[],
	startPosition: Vec2,
	toolIsUp: boolean,
	settings: GCodeSettings,
	lines: string[]
): Vec2 {
	const remaining = [...segments];
	let position = startPosition;
	let needsPlunge = toolIsUp;

	while (remaining.length > 0) {
		let bestIndex = 0;
		let bestDistance = Infinity;
		let enterAtStart = true;
		for (let index = 0; index < remaining.length; index++) {
			const segment = remaining[index];
			const dStart = distance(position, segment.start);
			const dEnd = distance(position, segment.end);
			const nearest = Math.min(dStart, dEnd);
			if (nearest < bestDistance) {
				bestDistance = nearest;
				bestIndex = index;
				enterAtStart = dStart <= dEnd;
			}
		}

		const segment = remaining.splice(bestIndex, 1)[0];
		const entry = enterAtStart ? segment.start : segment.end;
		const exit = enterAtStart ? segment.end : segment.start;

		if (needsPlunge || distance(position, entry) > 0.0001) {
			lines.push(g.rapidZ(settings.isolationSafeZ));
			lines.push(
				g.rapidXY(entry.x, entry.y, settings.useMachineRapids ? undefined : settings.xyRapidSpeed)
			);
			lines.push(g.moveZ(-settings.isolationDepth, settings.isolationPlungeSpeed));
			needsPlunge = false;
		}

		if (segment.arc) {
			const clockwise = enterAtStart ? segment.arc.clockwise : !segment.arc.clockwise;
			lines.push(
				g.arcMove(
					clockwise,
					exit.x,
					exit.y,
					segment.arc.center.x - entry.x,
					segment.arc.center.y - entry.y
				)
			);
		} else {
			lines.push(g.moveXY(exit.x, exit.y, settings.isolationXYSpeed));
		}

		position = exit;
	}

	return position;
}

interface DrillTarget {
	position: Vec2;
	diameterMm: number;
}

function drillTargets(board: BoardModel): DrillTarget[] {
	return board.pads
		.filter((pad) => pad.drill && pad.drill.diameter > 0 && pad.layers === 'through')
		.map((pad) => ({ position: pad.position, diameterMm: pad.drill!.diameter }));
}

function drillFiles(
	board: BoardModel,
	boardName: string,
	settings: GCodeSettings,
	generatedAt: Date,
	extension: string
): GCodeFile[] {
	const targets = drillTargets(board);
	const diameters = [...new Set(targets.map((t) => t.diameterMm))].sort((a, b) => a - b);
	const sideMirror = settings.drillSide === 'bottom' && settings.mirrorBottom;
	const transform = createOutputTransform(settings, board.width, board.height, sideMirror);

	return diameters.map((diameter) => {
		const lines = [
			...header(
				boardName,
				'Drill',
				settings.drillSide === 'bottom' ? 'Bottom (board flipped)' : 'Top',
				generatedAt,
				[`( Drill Size: ${diameter} mm )`]
			),
			...initialize(settings, settings.drillingSafeZ, settings.drillingSpindleRPM)
		];

		const holes = targets
			.filter((target) => target.diameterMm === diameter)
			.map((target) => transform.point(target.position));
		emitDrillSequence(holes, settings, lines);

		lines.push(...tearDown(settings, settings.drillingSafeZ));

		return {
			fileName: `${boardName}-drill-${diameter}mm${extension}`,
			label: `Drill ${diameter} mm holes (${holes.length})`,
			kind: 'drill' as const,
			drillDiameterMm: diameter,
			content: lines.join('\n') + '\n'
		};
	});
}

/** Drill each hole nearest-first from the current position. */
function emitDrillSequence(holes: Vec2[], settings: GCodeSettings, lines: string[]): void {
	const remaining = [...holes];
	let position: Vec2 = { x: 0, y: 0 };

	while (remaining.length > 0) {
		let bestIndex = 0;
		let bestDistance = Infinity;
		for (let index = 0; index < remaining.length; index++) {
			const d = distance(position, remaining[index]);
			if (d < bestDistance) {
				bestDistance = d;
				bestIndex = index;
			}
		}
		const hole = remaining.splice(bestIndex, 1)[0];

		lines.push(
			g.rapidXY(hole.x, hole.y, settings.useMachineRapids ? undefined : settings.xyRapidSpeed)
		);
		lines.push(g.moveZ(-settings.drillDepth, settings.drillingPlungeSpeed));
		lines.push(g.moveZ(settings.drillingSafeZ, settings.drillingRetractSpeed));

		position = hole;
	}
}

/**
 * Registration holes for double-sided machining: two holes on the horizontal
 * centerline, symmetric about the mirror axis, outside the left/right board
 * edges — they land at the same machine positions from either side. Run this
 * file first, then pin the blank.
 */
function registrationFile(
	board: BoardModel,
	boardName: string,
	settings: GCodeSettings,
	generatedAt: Date,
	extension: string
): GCodeFile {
	const margin = settings.registrationHoles.marginMm;
	const holesModel: Vec2[] = [
		{ x: -margin, y: board.height / 2 },
		{ x: board.width + margin, y: board.height / 2 }
	];
	const transform = createOutputTransform(settings, board.width, board.height, false);
	const holes = holesModel.map((hole) => transform.point(hole));

	const lines = [
		...header(boardName, 'Registration Drill', 'Either (run first)', generatedAt, [
			`( Drill Size: ${settings.registrationHoles.diameterMm} mm )`,
			'( Pin these holes to realign the blank after flipping )'
		]),
		...initialize(settings, settings.drillingSafeZ, settings.drillingSpindleRPM)
	];
	emitDrillSequence(holes, settings, lines);
	lines.push(...tearDown(settings, settings.drillingSafeZ));

	return {
		fileName: `${boardName}-registration${extension}`,
		label: `Registration holes ${settings.registrationHoles.diameterMm} mm — run first`,
		kind: 'registration',
		drillDiameterMm: settings.registrationHoles.diameterMm,
		content: lines.join('\n') + '\n'
	};
}
